// root/frontend/react-src/src/common/Navbar.js
import React from 'react';
import { Link } from 'react-router-dom';

class Navbar extends React.Component {
    render() {
        return (
            <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
                <div class="container">

                    {/* Brand */}
                    <Link className="navbar-brand" to="/">GymMate</Link>

                    {/* Collapse toggler button */}
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarDefault">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    {/* Collapsible navbar items */}
                    <div class="collapse navbar-collapse" id="navbarDefault">
                        <ul class="navbar-nav ml-auto">

                            <li class="nav-item">
                                <Link className="nav-link" to="/">Home</Link>
                            </li>

                            <li class="nav-item">
                                <Link className="nav-link" to="/programs">Programs</Link>
                            </li>

                            <li class="nav-item">
                                <Link className="nav-link" to="/exercises">Exercises</Link>
                            </li>

                            <li class="nav-item">
                                <Link className="nav-link" to="/profile">Profile</Link>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link">Sign up</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link">Log in</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        );
    }
}

export default Navbar;

// angular-src/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from '../../models/user';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
   public currentUser: User;

   constructor() { }

   ngOnInit() {
   }

   //TODO: remove this function
   testLogin(){
      const tempUser = new User();
      tempUser.username = "tempUser";
      this.currentUser = tempUser;
   }

   //TODO: remove this function
   testLogout(){
      this.currentUser = null;
   }
}

<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">

   <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" [routerLink]="['/']">GymMate</a>

      <!-- Collapse toggler button.  -->
      <button class="navbar-toggler" type="button" data-toggle="collapse"
         data-target="#navbarDefault">
         <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible navbar items-->
      <div class="collapse navbar-collapse" id="navbarDefault">
         <!--TODO: delete these test buttons-->
         <button class="btn btn-danger navbar-btn" (click)="testLogin()">testLogin</button>
         <button class="btn btn-danger navbar-btn" (click)="testLogout()">testLogout</button>
         <ul class="navbar-nav ml-auto">

            <li class="nav-item" routerLinkActive='active'
               [routerLinkActiveOptions]="{exact:true}">
               <a class="nav-link" routerLink="/">Home</a>
            </li>

            <li class="nav-item" routerLinkActive='active'>
               <a class="nav-link" routerLink="/programs">Programs</a>
            </li>

            <li class="nav-item" routerLinkActive='active'>
               <a class="nav-link" routerLink="/exercises">Exercises</a>
            </li>

            <li class="nav-item" routerLinkActive='active' *ngIf="currentUser">
               <a class="nav-link" routerLink="/profile">Profile</a>
            </li>

            <li class="nav-item" routerLinkActive='active' *ngIf="!currentUser">
               <a class="nav-link" routerLink="/signup">Sign up</a>
            </li>

            <li class="nav-item" routerLinkActive='active' *ngIf="!currentUser">
               <a class="nav-link" routerLink="/login">Log in</a>
            </li>

         </ul>
      </div>
   </div>
</nav>
